// Tables

/**
 * Assumption: Each table includes 'created_at' and 'updated_at'.
 * Future calculations in the backend should consider these assumptions.
*/

Table Roles {
  role_id int [pk]
  role_name TypesOfRoles
}

Table RoleUserRelation {
  role_user_id int [pk]
  role_id int // FK
  user_id int // FK
}

Table Users {
  user_id int [pk]
  username varchar
  password varchar
  email varchar
  division Division
}

Table TicketLog {
  ticked_id int [pk]
  action Action
  user_id int // FK
  entity_id int // FK
}

Table Entity {
  entity_id int [pk]
  type Type 
  isDeleted bool
  belongs_to_id int // FK
}

Table Clients {
  client_id int [pk]
  client_name varchar
  client_desc varchar
  high_growth bool
  division Division
  contract_pdf varchar
  logo varchar
}

Table ClientEmployeeRelation {
  client_employee_id int [pk]
  client_id int // FK
  employee_id int // FK
}

Table Projects {
  project_id int [pk]
  project_title varchar
  project_desc varchar
  start_date date
  has_expirated_date bool
  general_status ProjectStatus
  client_id int // FK
}

Table ExpirationDateProject {
  expiration_date_id int [pk]
  expiration_date date
  project_id int // FK
}

Table ClosedProject {
  closed_project_id int [pk]
  closed_status ClosedStatus
  closing_reason varchar
  project_id int // FK
}

Table Positions {
  position_id int [pk]
  position_title varchar
  division Division
  region Region
  tech_stack TechStack
  bill_rate float
  posting_type PostingType
  cross_division bool
  exclusivity bool
  working_hours int
  project_id int // FK
  // Demand Type is calculated
}

Table Comments {
  comment_id int [pk]
  comment varchar
  position_id int
}

Table Opening {
  opening_id int [pk]
  opening_status OpeningStatus
  opening_reason OpeningReason
  start_date date
  has_expiration_date bool
  position_id int // FK
  person_id int // FK
}

Table ExpirationDateOpening {
  expiration_date_id int [pk]
  expiration_date date
  opening_id int // FK
}

Table Applications {
  application_id int [pk]
  application_status ApplicationStatus
  position_id int // FK
  person_id int // FK
}

Table People {
  person_id int [pk]
  profile_picture varchar
  gender Gender
  phone varchar
  email varchar
  title varchar
  tech_stack TechStack
  division Division
  region Region
  people_status PeopleStatus
  movement_reason varchar
}

Table Employees { 
  employee_id int [pk]
  job varchar
  salary float
  job_grade JobGrade
  proposed_action ProposedAction
  employee_status EmployeeStatus
  employe_reason EmployeeReason
  contract_start_date date
  last_movement_at date
  person_id int // FK
}

Table Pipeline {
  pipeline_id int [pk]
  expected_salary float
  person_id int // FK
}

// Enums

Enum TypesOfRoles {
  Admin
  Account
  Resource
  Staffer
}

Enum Action {
  Create
  Update
  Delete
}

Enum Type {
  Clients
  Projects
  Positions
  Openings
  Applications
  People
  Users
}

Enum ProjectStatus {
  InPreparation
  Active
  Closed
}

Enum ClosedStatus {
  Completed
  Cancelled
}

Enum PostingType {
  NewHeadCount
  BackFill_Replacement
}

Enum OpeningStatus {
  New
  Filled
  Closed
  InProgress
  OnStandBy
}

Enum OpeningReason {
  InProgress
  OnStandby
  Hired
  Replacement
  BudgetProblem
  FilledByItself
  FilledByAnother
  NoReplied
}

Enum ApplicationStatus {
  Accepted
  ScheduleForInterview
  Rejected
}

Enum Gender {
  Male
  Female
  NonBinary
  NotWantedToSay
}

Enum JobGrade {
  C3
  C4
  C5
  C6
}

Enum TechStack {
  Java
  React
  Python
  Automation
  Golang
  JavaScript
  NET
  Angular
  Appian
  PowerApps
  ManualTester
  Kotlin
  UX
  iOS
}

Enum ProposedAction {
  ProjectSearch
  UsingInInternalProject
  UpSkillingCrossTraining 
  BackupShadowOtherProjects 
  ResourcePool
  NoActionRequired
  Others
  Attrition
}

enum EmployeeReason {
  InTraining
  InductionOrientation
  ShadowResource
  AwaitingClientConfirmationJoining
  MaternityLeave
  SabbaticalOtherLeave
  PreviousClientAttrition
  PreviousClientHCReduction
  TransitionBetweenProjects
  NoAvailableProjects
  InternalProject
  MovedToBilling
  PerformanceIssuesPIP
  Other
  Intern
}


Enum Division {
  BRAZIL
  MEXICO
  CSA
  US
}

enum Region {
  // Mexico
  CDMX 
  CUU 
  HMO 
  MID 
  SLP 
  // Brazil
  CAMPINA 
  SAO_PAULO 
  // Central and South American
  COLOMBIA 
  PERU 
  COSTA_RICA 
  ARGENTINA 
  DOMINICANA 
  // United States
  DALLAS 
  PHOENIX 
}


Enum PeopleStatus {
  Pipeline
  Bench
  Billing
}

Enum EmployeeStatus {
  OnHired
  LayOff
  Resigned
}

// RoleUserRelation
Ref: "Roles"."role_id" < "RoleUserRelation"."role_id"
Ref: "Users"."user_id" < "RoleUserRelation"."user_id"

// Client
Ref: "Clients"."client_id" < "Projects"."client_id"

// TicketLog
Ref: "Users"."user_id" < "TicketLog"."user_id"

// Entity
Ref: "TicketLog"."entity_id" - "Entity"."belongs_to_id"
Ref: "Clients"."client_id" - "Entity"."belongs_to_id"
Ref: "Projects"."project_id" - "Entity"."belongs_to_id"
Ref: "Positions"."position_id" - "Entity"."belongs_to_id"
Ref: "Opening"."opening_id" - "Entity"."belongs_to_id"
Ref: "Applications"."application_id" - "Entity"."belongs_to_id"
Ref: "People"."person_id" - "Entity"."belongs_to_id"
Ref: "Users"."user_id" - "Entity"."belongs_to_id"

// ClientEmployeeRelation
Ref: "Clients"."client_id" <  "ClientEmployeeRelation"."client_employee_id"
Ref: "Employees"."employee_id" <  "ClientEmployeeRelation"."client_employee_id"

// Projects
Ref: "Projects"."project_id" < "Positions"."project_id" 
Ref: "ExpirationDateProject"."project_id" - "Projects"."project_id"
Ref: "ClosedProject"."project_id" - "Projects"."project_id"

// Job Positions
Ref: "Positions"."position_id" < "Applications"."position_id"
Ref: "Positions"."position_id" < "Opening"."position_id"
Ref: "Applications"."person_id" - "People"."person_id"
Ref: "Opening"."person_id" - "People"."person_id"
Ref: "ExpirationDateOpening"."opening_id" - "Opening"."opening_id"
Ref: "Comments"."position_id" - "Positions"."position_id"

// People
Ref: "People"."person_id" - "Employees"."person_id"
Ref: "People"."person_id" - "Pipeline"."person_id"