// Tables

/**
 * Assumption: Each table includes 'created_at', 'updated_at', and 'deleted_at' columns.
 * Future calculations in the backend should consider these assumptions.
*/

Table Roles {
  role_id int [pk]
  role_name TypesOfRoles
}

Table RoleUserRelation {
  role_user_id int [pk]
  role_id int // FK
  user_id int // FK
}

Table Users {
  user_id int [pk]
  username varchar
  password varchar
  email varchar
}

Table Clients {
  client_id int [pk]
  client_name varchar
  client_desc varchar
  high_growth bool
  division varchar
  contract_pdf varchar
  logo varchar
  created_by int // FK
  updated_by int // FK
}

Table ClientEmployeeRelation {
  client_employee_id int [pk]
  client_id int // FK
  employee_id int // FK
}

Table Projects {
  project_id int [pk]
  project_title varchar
  project_desc varchar
  publication_date date
  has_expirated_date bool
  general_status ProjectStatus
  client_id int // FK
  created_by int // FK
  updated_by int // FK
}

Table ExpirationDateProject {
  expiration_date_id int [pk]
  expiration_date date
  project_id int // FK
}

Table ClosedProject {
  closed_project_id int [pk]
  closed_status enum
  closing_reason varchar
  project_id int // FK
}

Table Positions {
  position_id int [pk]
  position_title varchar
  division varchar
  region varchar
  tech_stack varchar
  posting_type PostingType
  cross_division bool
  exclusivity bool
  project_id int // FK
  created_by int // FK
  updated_by int // FK
}

Table Opening {
  opening_id int [pk]
  opening_status OpeningStatus
  opening_reason OpeningReason
  publication_date date
  has_expirated_date bool
  position_id int // FK
  person_id int // FK
  created_by int // FK
  updated_by int // FK
}

Table ExpirationDateOpening {
  expiration_date_id int [pk]
  expiration_date date
  opening_id int // FK
}

Table Applications {
  application_id int [pk]
  application_status ApplicationStatus
  position_id int // FK
  person_id int // FK
  created_by int // FK
  updated_by int // FK
}

Table People {
  person_id int [pk]
  phone varchar
  email varchar
  job_title varchar
  tech_stack varchar
  region varchar
  division varchar
  job_grade varchar
  is_fired bool
  people_status PeopleStatus
  created_by int // FK
  updated_by int // FK
}

Table Candidate {
  candidate_id int [pk]
  expected_salary float
  person_id int // FK
}

Table Employees { 
  employee_id int [pk]
  salary float
  hired_date date
  reason varchar
  proposed_action varchar
  contract_start_date date 
  work_hours int 
  person_id int // FK
}

Table Pipeline {
  pipeline_id int [pk]
  candidate_id int // FK
}

Table Bench {
  bench_id int [pk]
  employee_id int // FK
  candidate_id int // FK
}

Table Billing {
  billing_id int [pk]
  employee_id int // FK
}

// Enums

Enum TypesOfRoles {
  Admin
  Account
  Resource
  Staffer
}

Enum ProjectStatus {
  InPreparation
  Active
  Closed
}

Enum PostingType {
  NewHeadCount
  BackFill_Replacement
}

Enum OpeningStatus {
  New
  Filled
  Closed
  InProgress
  OnStandBy
}

Enum OpeningReason {
  InProgress
  OnStandby
  Hired
  Replacement
  BudgetProblem
  FilledByItself
  FilledByAnother
  NoReplied
}

Enum ApplicationStatus {
  Accepted
  ScheduleForInterview
  Rejected
}

Enum PeopleStatus {
  Pipeline
  Bench
  Billing
}


// RoleUserRelation
Ref: "Roles"."role_id" < "RoleUserRelation"."role_user_id"
Ref: "Users"."user_id" < "RoleUserRelation"."role_user_id"

// Client
Ref: "Clients"."client_id" < "Projects"."client_id" 

// ClientEmployeeRelation
Ref: "Clients"."client_id" <  "ClientEmployeeRelation"."client_employee_id"
Ref: "Employees"."employee_id" <  "ClientEmployeeRelation"."client_employee_id"

// Projects
Ref: "Projects"."project_id" < "Positions"."project_id" 
Ref: "ExpirationDateProject"."project_id" - "Projects"."project_id"
Ref: "ClosedProject"."project_id" - "Projects"."project_id"

// Job Positions
Ref: "Positions"."position_id" < "Applications"."position_id"
Ref: "Positions"."position_id" < "Opening"."position_id"
Ref: "Applications"."person_id" - "People"."person_id"
Ref: "Opening"."person_id" - "People"."person_id"
Ref: "ExpirationDateOpening"."opening_id" - "Opening"."opening_id"

// People
Ref: "People"."person_id" - "Candidate"."person_id"
Ref: "People"."person_id" - "Employees"."person_id"

// Candidate
Ref: "Candidate"."candidate_id" - "Bench"."candidate_id"
Ref: "Candidate"."candidate_id" - "Pipeline"."candidate_id"

// Employee
Ref: "Employees"."employee_id" - "Bench"."employee_id"
Ref: "Employees"."employee_id" - "Billing"."employee_id"

// Account manager
Ref: "Users"."user_id" < "Clients"."created_by"
Ref: "Users"."user_id" < "Clients"."updated_by"
Ref: "Users"."user_id" < "Projects"."created_by"
Ref: "Users"."user_id" < "Projects"."updated_by"
Ref: "Users"."user_id" < "Positions"."created_by"
Ref: "Users"."user_id" < "Positions"."updated_by"
Ref: "Users"."user_id" < "Opening"."created_by"
Ref: "Users"."user_id" < "Opening"."updated_by"

// Staffer 
Ref: "Users"."user_id" < "Applications"."created_by"
Ref: "Users"."user_id" < "Applications"."updated_by"

// Resource
Ref: "Users"."user_id" < "People"."created_by"
Ref: "Users"."user_id" < "People"."updated_by"