Table Clients {
    client_id int [pk]
    contract_pdf varchar
    logo varchar
    client_name varchar
    client_desc varchar
    exclusivity varchar
    high_growth bool
    division varchar
}

Table Projects {
    project_id int [pk]
    project_title varchar
    project_desc varchar
    bill_rate float
    publication_date date
    expiration_date date
    project_status int
    client_id int
}

Table Positions {
    position_id int [pk]
    position_title varchar
    position_desc varchar
    publication_type varchar
    cross_division bool
    division varchar
    region varchar
    tech_stack varchar
    demand_curation varchar
    exclusivity bool
    project_id int
}

Table Vacancies {
    vacancy_id int [pk]
    reason varchar //NEED REVISION WITH VIDEO
    position_id int
    person_id int 
}

Table Persons {
    person_id int [pk]
    region varchar
    division varchar
    job_title varchar
    job_grade varchar
    tech_stack varchar
    registration_date date
    phone varchar
    email varchar
    pipeline_id int
    employee_id int 
}

Table Employees { 
  employee_id int [pk]
  salary float
  hired_date date
  bench_id int
  billing_id int
}

Table Bench {
  bench_id int [pk]
  benched_since date
  days_on_bench int
}

Table Pipeline {
  pipeline_id int [pk]
  expected_salary float
  in_pipeline_since date
  days_in_pipeline int
  person_id int 
}

Table Billing {
  billing_id int [pk]
  billing_since date
  days_billing int
}

Table Client_Employee_Relation {
    employee_id int 
    contract_start_date date
    last_client varchar
    current_client varchar
    work_hours int
    client_id int 
    client_name varchar
}

Table Users {
    user_id int [pk]
    username varchar
    password varchar
    email varchar
    role varchar
}

//This Transaction Table is used to know which employees 
Table Application {
  status varchar
  position_id int //COMPOUND
  person_id int  //KEY
}


Ref: "Projects"."client_id" > "Clients"."client_id"
Ref: "Positions"."project_id" > "Projects"."project_id"
Ref: "Vacancies"."position_id" > "Positions"."position_id"
Ref: "Positions"."position_id" < "Application"."position_id"
Ref: "Persons"."pipeline_id" - "Pipeline"."pipeline_id"
Ref: "Persons"."employee_id" - "Employees"."employee_id"
Ref: "Employees"."bench_id" - "Bench"."bench_id"
Ref: "Employees"."billing_id" - "Billing"."billing_id"
Ref: "Application"."person_id" - "Persons"."person_id"
Ref: "Vacancies"."person_id" - "Persons"."person_id" 
Ref: "Employees"."employee_id" - "Client_Employee_Relation"."employee_id"
Ref: "Clients"."client_id" - "Client_Employee_Relation"."client_id"
